T20_DBT_PROJECT_TESTING_1:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: NSZFGKQ-KM67393
      user: RAUNITRAJ161021
      password: R@unitr@j@1234$
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: RAUNIT_T20_DBT
      schema: T20_DATA_TRANSFORM