{{
    config(
        materialized='incremental',
        unique_key=['SEASON','MATCHID','TEAMID','PLAYERID'],
        incremental_strategy='merge'
    )
}}

WITH playerstats AS (
    SELECT 
        COALESCE(PS.SEASON::NUMBER, NULL) AS SEASON,
        COALESCE(BA.MATCHID::NUMBER, NULL) AS MATCHID,
        COALESCE(BA.INNINGID::NUMBER, NULL) AS INNING,
        COALESCE(T.TEAMID::NUMBER, NULL) AS TEAMID,
        COALESCE(T.TEAMNAME::VARCHAR, NULL) AS TEAMNAME,
        COALESCE(P.PLAYERID::NUMBER, NULL) AS PLAYERID,
        COALESCE(P.PLAYERNAME::VARCHAR, NULL) AS PLAYERNAME,
        COALESCE(BA.PLAYORDER::NUMBER, NULL) AS PLAYERORDER,
        COALESCE(BA.RUNS::NUMBER, NULL) AS RUNS_MADE,
        COALESCE(BA.BALLS::NUMBER, NULL) AS BALLS_PLAYED,
        COALESCE(BA.BOUNDERIES::NUMBER, NULL) AS FOURS_HITTEN,
        COALESCE(BA.SIXES::NUMBER, NULL) AS SIXES_HITTEN,
        COALESCE(BA.DOTSBALLS::NUMBER, NULL) AS DOTBALLS_PLAYED,
        COALESCE(BO.BALLSBOWLED::NUMBER, NULL) AS BOWLS_BOWLED,
        COALESCE(BO.MAIDENS::NUMBER, NULL) AS MAIDEN_TAKEN,
        COALESCE(BO.DOTBALLS::NUMBER, NULL) AS DOTSBALLS_THROWN,
        COALESCE(BO.RUNSGIVEN::NUMBER, NULL) AS RUNS_GIVEN,
        COALESCE(BO.BOUNDERIESCONCEDED::NUMBER, NULL) AS BOUNDERIES_CONCEDED,
        COALESCE(BO.SIXESCONCEDED::NUMBER, NULL) AS SIXES_CONCEDED,
        COALESCE(BO.NOBALLS::NUMBER, NULL) AS NOBALLS_GIVEN,
        COALESCE(BO.WIDES::NUMBER, NULL) AS WIDES_GIVEN,
        COALESCE(BO.WICKETSTAKEN::NUMBER, NULL) AS WICKETS_TAKEN,
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS INSERTED_AT
    FROM {{ ref('STG_RAW_PLAYER') }} AS P
    LEFT JOIN {{ ref('STG_RAW_PLAYERSEASON') }} AS PS ON P.PLAYERID = PS.PLAYERID
    LEFT JOIN {{ ref('STG_RAW_TEAM') }} AS T ON PS.TEAMID = T.TEAMID
    LEFT JOIN {{ ref('STG_RAW_BATTINGCARD') }} AS BA ON P.PLAYERID = BA.BATSMANID
    LEFT JOIN {{ ref('STG_RAW_BOWLINGCARD') }} AS BO 
        ON P.PLAYERID = BO.BOWLERID 
        AND BA.MATCHID = BO.MATCHID 
        AND BA.INNINGID = BO.INNINGID

    {% if is_incremental() %}
        WHERE INSERTED_AT > (SELECT COALESCE(MAX(INSERTED_AT), '1900-01-01') FROM {{ this }})
    {% endif %}
),
deduped AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY SEASON, MATCHID, INNING, TEAMID, PLAYERID
               ORDER BY INSERTED_AT DESC
           ) AS rn
    FROM playerstats
)
SELECT *
FROM deduped
WHERE rn = 1