{{
    config(
        materialized='view'
    )
}}

SELECT SEASON, TEAMNAME, PLAYERID, PLAYERNAME, {{add_boundries('SIXES_HITTEN','FOURS_HITTEN')}} AS BOUNDERIES FROM {{ref('STG_BRONZE_PLAYERSTATS')}} GROUP BY SEASON, TEAMNAME, PLAYERID, PLAYERNAME